#!/usr/bin/env node
/**
 * Report Generator - 自动生成SEO+GEO双维度报告
 */

import { createClient } from '@supabase/supabase-js';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const supabase = createClient(
  'https://fixemvsckapejyfwphft.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpeGVtdnNja2FwZWp5ZndwaGZ0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTkxNDczNSwiZXhwIjoyMDg3NDkwNzM1fQ.q_mgJQlae4B0AJMv9RziN2MzjVRKylG-06WIKFoG434'
);

async function generateReport(clientId, type = 'full') {
  console.log(`📊 Generating ${type} report for client: ${clientId}`);
  
  // 获取客户数据
  const { data: client, error } = await supabase
    .from('clients')
    .select('*')
    .eq('id', clientId)
    .single();
  
  if (error || !client) {
    console.error('Client not found:', error);
    return;
  }
  
  const reportDate = new Date().toISOString().split('T')[0];
  const outputDir = path.join(__dirname, `../../outputs/${clientId}/reports`);
  await fs.mkdir(outputDir, { recursive: true });
  
  let reportContent = '';
  
  if (type === 'full' || type === 'seo') {
    reportContent += generateSEOReport(client);
  }
  
  if (type === 'full' || type === 'geo') {
    reportContent += generateGEOReport(client);
  }
  
  if (type === 'full') {
    reportContent += generateDualStrategy(client);
  }
  
  // 添加报告头部
  const fullReport = `# ${client.business_name} - SEO + GEO Analysis Report
**Report Date**: ${reportDate}  
**Client ID**: ${clientId}  
**Industry**: ${client.industry}

---

${reportContent}

---

*Generated by GEO + SEO Dual-Dimension Analysis Engine*
`;
  
  const reportPath = path.join(outputDir, `${type}-report-${reportDate}.md`);
  await fs.writeFile(reportPath, fullReport);
  
  console.log(`✅ Report saved: ${reportPath}`);
  return reportPath;
}

function generateSEOReport(client) {
  const seoScore = client.seo_score || 0;
  const techScore = client.tech_seo_score || 0;
  const contentScore = client.content_seo_score || 0;
  const authorityScore = client.authority_seo_score || 0;
  
  return `
## 🔍 SEO Analysis

### Overall SEO Score: ${seoScore}/100

**Component Breakdown:**
| Component | Score | Status |
|-----------|-------|--------|
| Technical SEO | ${techScore}/100 | ${getStatusEmoji(techScore)} |
| Content SEO | ${contentScore}/100 | ${getStatusEmoji(contentScore)} |
| Authority SEO | ${authorityScore}/100 | ${getStatusEmoji(authorityScore)} |

### Technical SEO Assessment
${generateTechnicalSEOSection(techScore)}

### Content SEO Assessment  
${generateContentSEOSection(contentScore)}

### Authority SEO Assessment
${generateAuthoritySEOSection(authorityScore)}

### Target Keywords
${(client.target_keywords || []).map(k => `- ${k}`).join('\n') || 'No keywords configured'}

### SEO Recommendations
${generateSEORecommendations(seoScore, techScore, contentScore, authorityScore)}
`;
}

function generateGEOReport(client) {
  const geoScore = client.geo_score || 0;
  const aiScore = client.ai_citation_score || 0;
  const kgScore = client.knowledge_graph_score || 0;
  
  return `
## 🤖 GEO (AI Citation) Analysis

### Overall GEO Score: ${geoScore}/100

**Component Breakdown:**
| Component | Score | Status |
|-----------|-------|--------|
| AI Citations | ${aiScore}/100 | ${getStatusEmoji(aiScore)} |
| Knowledge Graph | ${kgScore}/100 | ${getStatusEmoji(kgScore)} |

### AI Platform Presence
${generateAIPresenceSection(aiScore)}

### Knowledge Graph Status
${generateKnowledgeGraphSection(kgScore)}

### GEO Recommendations
${generateGEORecommendations(geoScore, aiScore, kgScore)}
`;
}

function generateDualStrategy(client) {
  const seoScore = client.seo_score || 0;
  const geoScore = client.geo_score || 0;
  const dualScore = Math.round((seoScore + geoScore) / 2);
  
  return `
## 📊 Dual-Dimension Strategy

### Combined Score: ${dualScore}/100

**Score Comparison:**
\`\`\`
SEO:  ${'█'.repeat(Math.floor(seoScore / 5))}${'░'.repeat(20 - Math.floor(seoScore / 5))} ${seoScore}%
GEO:  ${'█'.repeat(Math.floor(geoScore / 5))}${'░'.repeat(20 - Math.floor(geoScore / 5))} ${geoScore}%
\`\`\`

### Priority Matrix
${generatePriorityMatrix(seoScore, geoScore)}

### 30-Day Action Plan
${generateActionPlan(seoScore, geoScore)}

### Expected Results
| Metric | Current | 30 Days | 90 Days |
|--------|---------|---------|---------|
| SEO Score | ${seoScore} | ${Math.min(seoScore + 15, 100)} | ${Math.min(seoScore + 30, 100)} |
| GEO Score | ${geoScore} | ${Math.min(geoScore + 12, 100)} | ${Math.min(geoScore + 25, 100)} |
| Dual Score | ${dualScore} | ${Math.min(dualScore + 13, 100)} | ${Math.min(dualScore + 27, 100)} |

### Investment & ROI
- **Estimated Monthly Investment**: $500 - $2,000
- **Expected ROI**: 300% within 6 months
- **Break-even Timeline**: 3-4 months
`;
}

function getStatusEmoji(score) {
  if (score >= 80) return '🟢 Excellent';
  if (score >= 60) return '🟡 Good';
  if (score >= 40) return '🟠 Needs Work';
  return '🔴 Critical';
}

function generateTechnicalSEOSection(score) {
  if (score >= 80) return '✅ Technical foundation is solid. Site speed, mobile optimization, and schema markup are all performing well.';
  if (score >= 60) return '⚠️ Technical SEO needs minor improvements. Focus on page speed optimization and mobile responsiveness.';
  return '🔴 Critical technical issues detected. Immediate action required on site speed, indexing, and mobile compatibility.';
}

function generateContentSEOSection(score) {
  if (score >= 80) return '✅ Content strategy is effective. Good keyword coverage, content depth, and freshness.';
  if (score >= 60) return '⚠️ Content needs expansion. Add more comprehensive pillar pages and FAQ sections.';
  return '🔴 Content is thin and under-optimized. Major content creation initiative needed.';
}

function generateAuthoritySEOSection(score) {
  if (score >= 80) return '✅ Strong backlink profile and brand authority. Continue current link building strategy.';
  if (score >= 60) return '⚠️ Authority building in progress. Need more high-quality backlinks from industry sites.';
  return '🔴 Low domain authority. Aggressive link building and PR campaign required.';
}

function generateAIPresenceSection(score) {
  if (score >= 60) return '✅ Good AI platform presence. Brand is being cited by Perplexity and other AI systems.';
  if (score >= 40) return '⚠️ Limited AI citations. Need to optimize content for AI-friendly formats.';
  return '🔴 Minimal AI presence. Content not being cited by major AI platforms.';
}

function generateKnowledgeGraphSection(score) {
  if (score >= 60) return '✅ Knowledge Graph presence established. Google recognizes the brand entity.';
  if (score >= 40) return '⚠️ Limited Knowledge Graph presence. Need to enhance structured data and entity signals.';
  return '🔴 Not present in Knowledge Graph. Entity optimization campaign needed.';
}

function generateSEORecommendations(seo, tech, content, authority) {
  const recs = [];
  if (tech < 70) recs.push('1. **Technical Priority**: Fix page speed issues (target LCP < 2.5s)');
  if (content < 70) recs.push('2. **Content Priority**: Create 3 pillar pages targeting primary keywords');
  if (authority < 70) recs.push('3. **Authority Priority**: Build 5 high-quality backlinks from DA 50+ sites');
  if (recs.length === 0) recs.push('1. **Maintenance**: Continue current SEO strategy');
  return recs.join('\n');
}

function generateGEORecommendations(geo, ai, kg) {
  const recs = [];
  if (ai < 60) recs.push('1. **AI Optimization**: Add FAQ schema and direct answer formats to content');
  if (kg < 50) recs.push('2. **Knowledge Graph**: Submit to Wikidata and optimize Google Business Profile');
  if (recs.length === 0) recs.push('1. **Expansion**: Increase AI platform visibility with authoritative content');
  return recs.join('\n');
}

function generatePriorityMatrix(seo, geo) {
  if (seo < geo) {
    return '🎯 **Priority: SEO Focus**\nGEO score is higher. Concentrate efforts on SEO improvements while maintaining GEO performance.';
  } else if (geo < seo) {
    return '🤖 **Priority: GEO Focus**\nSEO score is higher. Focus on AI citation optimization and knowledge graph presence.';
  }
  return '⚖️ **Priority: Balanced**\nBoth scores are equal. Implement dual-dimension strategy evenly.';
}

function generateActionPlan(seo, geo) {
  const actions = [];
  
  // Week 1
  actions.push(`**Week 1: Foundation**\n- Technical SEO audit and fixes\n- Schema markup implementation\n- Keyword research refinement`);
  
  // Week 2  
  actions.push(`**Week 2: Content**\n- Create/update pillar pages\n- Add FAQ sections\n- Optimize for featured snippets`);
  
  // Week 3
  actions.push(`**Week 3: Authority**\n- Backlink outreach campaign\n- Local citation building\n- PR and media mentions`);
  
  // Week 4
  actions.push(`**Week 4: GEO**\n- AI-friendly content formatting\n- Knowledge graph optimization\n- Brand mention monitoring setup`);
  
  return actions.join('\n\n');
}

// CLI usage
const clientId = process.argv[2];
const reportType = process.argv[3] || 'full';

if (!clientId) {
  console.log('Usage: node generate-report.js [client_id] [type: full|seo|geo]');
  console.log('Example: node generate-report.js geo_123 full');
  process.exit(1);
}

generateReport(clientId, reportType).then(path => {
  console.log('\n✅ Report generation complete!');
  console.log(`📄 Report saved to: ${path}`);
}).catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
